name: School Grounds overpass api query for 

on:
  schedule:
    - cron: '0 0 * * *' # Scheduled for 00:00.   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout private repository 
        uses: actions/checkout@v3
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: install python packages
        run: pip install -r requirements.txt

      - name: execute py script
        run: python schoolgrounds.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a --allow-empty

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  